### ISSUE TITLE
Use scope without a formatter string

### ISSUE THREAD

**Issue by pardahlman** [Korla/Zipkin.Demo#2]
You should be able to log properties straight to `fields` by using a dictionary

```csharp
using (logger.BeginScope(new Dictionary<string, object> {{"value1", "A value"}, {"value2", 1337}}))
{
  logger.LogInformation("A Microsoft log");
}
```

![image](https://user-images.githubusercontent.com/1032755/50332797-87080000-0503-11e9-94b6-2dc254a10f2f.png)

Perhaps a bit verbose, but you could hide this in extension methods...?

**Comment by Korla** [comment]
I really like the output of this. Perhaps an extension method which converts an object to a dictionary would help with the API. I am thinking in a broader scenario where there is a LogContext contract, like this:

```c#
interface ILogContext
{
  string Value1 { get; }
  DateTime Value2 { get; }
}
```
And the logs are enriched using some Application.ILogger interface:
```c#
interface ILogger {
  void Log(LogLevel level, string message);
  IDisposable EnrichWithLogContext(ILogContext context);
}
```

Here it would be nice not to update the `EnrichWithLogContext`-implementation(s) each time a property is added to the `ILogContext`. Something like [this](https://stackoverflow.com/questions/51501969/reflection-get-all-properties-that-implements-an-interface-in-a-parameter-objec) maybe.

**Comment by pardahlman** [comment]
Sounds good - perhaps avoid `ILogContext` as it (at least in Serilog) refers to the _entire_ context with all properties currently in scope.

As it is common to enrich with one property, perhaps an extension like this could be useful

```csharp
public static class LoggerExtensions
{
  public static IDisposable BeginScope(this ILogger logger, string key, object value)
    => logger.BeginScope(new Dictionary<string, object> {{key, value}});
}
```

And being used it would look like

```csharp
using (logger.BeginScope("value1", "A value"))
using (logger.BeginScope("value2", 1337))
{
  logger.LogInformation("A Microsoft log");
}
```

In this example, we allocate two dictionaries, which isn't desirable 🤔
